services:
  atomic-server:
    # You can create a .env using `atomic-server generate-dotenv`
    env_file: ".env"
    image: joepmeneer/atomic-server
    container_name: atomic-server
    ports:
      - 80:80
    volumes:
      - atomic-storage:/atomic-storage
volumes:
  atomic-storage:
    driver: local
