[package]
authors = ["Joep Meindertsma <joep@argu.co>"]
description = "CLI tool to create, store, query, validate and convert Atomic Data"
edition = "2021"
license = "MIT"
name = "atomic-cli"
readme = "README.md"
repository = "https://github.com/joepio/atomic-data-rust"
version = "0.31.1"

[dependencies]
atomic_lib = {version = "0.31", path = "../lib", features = ["config", "rdf"]}
clap = {version = "3", features = ["cargo"]}
colored = "2"
dirs = "3"
edit = {version = "0.1", optional = true}
promptly = "0.3"
regex = "1"

[dev-dependencies]
assert_cmd = "2"

[features]
default = ["native"]
# Non-wasi interface. These features cannot be compiled to WASI.
native = ["edit"]
