[package]
authors = ["Joep Meindertsma <joep@ontola.io>"]
description = "Create, share and model Atomic Data with this graph database server."
edition = "2018"
license = "MIT"
name = "atomic-server"
repository = "https://github.com/joepio/atomic-data-rust"
version = "0.26.3"

[dependencies]
acme-lib = "0.8.1"
actix = "0.10.0"
actix-cors = "0.5.4"
actix-files = "0.5.0"
actix-web = {version = "3.3.2", features = ["rustls"]}
actix-web-actors = "3.0.0"
atomic_lib = {version = "0.26.2", path = "../lib", features = ["config", "db", "rdf"]}
chrono = "0.4.19"
clap = "3.0.0-beta.5"
dirs = "3.0.1"
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.16"
heim = "0.0.11"
log = "0.4.11"
open = {version = "2.0.1", optional = true}
promptly = "0.3.0"
regex = "1.4.2"
rustls = "0.18.1"
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0.60"
tokio = {version = "1.4.0", features = ["time"]}
tray-item = {version = "0.4.0-alpha", optional = true}

[features]
desktop = ["tray-item", "open"]
