[package]
authors = ["Joep Meindertsma <joep@ontola.io>"]
description = "Create, share and model Atomic Data with this graph database server."
edition = "2021"
license = "MIT"
name = "atomic-server"
repository = "https://github.com/joepio/atomic-data-rust"
version = "0.28.2"
[dependencies]
actix = "0.10.0"
actix-cors = "0.5.4"
actix-files = "0.5.0"
actix-web-actors = "3.0.0"
chrono = "0.4.19"
clap = "3.0.0-beta.5"
dirs = "3.0.1"
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.16"
log = "0.4.11"
promptly = "0.3.0"
regex = "1.4.2"
rio_api = "0.6.1"
rio_turtle = "0.6.1"
serde_json = "1.0.60"
sysinfo = "0.20.5"
tantivy = "0.16.1"

[dependencies.acme-lib]
optional = true
version = "0.8.1"

[dependencies.actix-web]
features = ["rustls"]
version = "3.3.2"

[dependencies.atomic_lib]
features = ["config", "db", "rdf"]
path = "../lib"
version = "0.28.2"

[dependencies.open]
optional = true
version = "2.0.1"

[dependencies.rustls]
optional = true
version = "0.18.1"

[dependencies.serde]
features = ["derive"]
version = "1.0.118"

[dependencies.tokio]
features = ["time"]
version = "1.4.0"

[dependencies.tray-item]
optional = true
version = "0.4.0-alpha"

[dev-dependencies]
# Currently only used for testing, the other actix is included in the web crate
actix-rt = "1.1.1"

[features]
default = ["https"]
desktop = ["tray-item", "open"]
https = ["acme-lib", "rustls"]
