[package]
authors = ["Joep Meindertsma <joep@ontola.io>"]
default-run = "atomic-server"
description = "Create, share and model Atomic Data with this graph database server. Run atomic-server without any arguments to start the server. Use --help to learn about the options."
edition = "2021"
license = "MIT"
name = "atomic-server"
repository = "https://github.com/joepio/atomic-data-rust"
version = "0.31.0"

[[bin]]
name = "atomic-server"
path = "src/bin.rs"

[dependencies]
actix = "0.12.0"
actix-cors = "0.6.0"
actix-files = "0.6.0"
actix-multipart = "0.4.0"
actix-web-actors = "4.1.0"
async-std = "1.10.0"
awc = "3.0.0-beta.21"
chrono = "0.4.19"
dirs = "3.0.1"
dotenv = "0.15.0"
futures = "0.3.16"
promptly = "0.3.0"
regex = "1.4.2"
rio_api = "0.6.1"
rio_turtle = "0.6.1"
rustls-pemfile = "0.2.1"
sanitize-filename = "0.3.0"
serde_json = "1.0.60"
static-files = "0.2.3"
sysinfo = "0.20.5"
tantivy = "0.16.1"
tracing = "0.1.31"
tracing-actix-web = "0.5.1"
tracing-chrome = "0.4.0"
tracing-log = "0.1.2"
urlencoding = "2.1.0"

[dependencies.acme-lib]
optional = true
version = "0.8.1"

[dependencies.actix-web]
features = ["rustls"]
version = "4.0.1"

[dependencies.atomic_lib]
features = ["config", "db", "rdf"]
path = "../lib"
version = "0.31.0"

[dependencies.clap]
features = ["derive", "env", "cargo"]
version = "3.1.0"

[dependencies.rustls]
optional = true
version = "0.20.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.136"

[dependencies.tokio]
features = ["time"]
version = "1.17.0"

[dependencies.tracing-subscriber]
features = ["env-filter"]
version = "0.3.9"

[dependencies.actix-web-static-files]
git = "https://github.com/kilork/actix-web-static-files.git"
rev = "2d3b6160f0de4ba061c5d76b5704f34fb677f6df"
# version = "0.4.0"

[dev-dependencies]
actix-rt = "2.5.1"

[build-dependencies]
static-files = "0.2.3"

[features]
default = ["https"]
https = ["acme-lib", "rustls"]

[lib]
name = "atomic_server_lib"
path = "src/lib.rs"
