name: Docker

on:
  workflow_dispatch:
  workflow_run:
    workflows: [main]
    types: [completed]
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Build Docker images and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # Required for multi-platform
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Required for multi-platform
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: joepmeneer
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: joepmeneer/atomic-server
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: joepmeneer/atomic-server:latest
          labels: ${{ steps.meta.outputs.labels }}
