name: Build docker image

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: joepmeneer
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: joepmeneer/atomic-server

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          use: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: joepmeneer/atomic-server:rust-alpine
          labels: ${{ steps.meta.outputs.labels }}
